wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.page, name="page"),
    path("error", views.error, name="error"),
    path("newPage", views.newPage, name="newPage"),
    path("randomPage", views.randomPage, name="randomPage"),
    path("searchPage", views.searchPage, name="searchPage"),
    path("editPage/<str:name>", views.editPage, name="editPage")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.urls import reverse
from django import forms
import markdown2
from . import util
from django.http import HttpResponseRedirect
import random

class editPageForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea)

class newPageForm(forms.Form):
    title =  forms.CharField()
    body = forms.CharField(widget=forms.Textarea)

def markdownToHTML(name):
    content = markdown2.markdown(util.get_entry(name))
    return content

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def page(request, name):
    if name not in util.list_entries():
        return HttpResponseRedirect(reverse("encyclopedia:error"))
    else:
        content = markdownToHTML(name)
        return render(request, "encyclopedia/page.html", {
            "content": content,
            "title": name,
        })
    
def error(request):
    return render(request, "encyclopedia/error.html")

def newPage(request):
    if request.method == "POST":
        form = newPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            body = form.cleaned_data["body"]
            
            if title not in util.list_entries():
                util.save_entry(title, body)
                return HttpResponseRedirect("wiki/"+title)
            else:
                return render(request, "encyclopedia/newPage.html", {
                    "form": newPageForm(),
                    "Error": True,
                })
            
    return render(request, "encyclopedia/newPage.html", {
        "form": newPageForm(),
    })

def randomPage(request):
    list = random.choice(util.list_entries())
    return HttpResponseRedirect("wiki/"+list)

def searchPage(request):
    if request.method == "POST":
        search = request.POST['q']
        if search in util.list_entries():
            return HttpResponseRedirect("wiki/"+search)
        else:
            for entry in util.list_entries():
                if search in entry:
                    return HttpResponseRedirect("wiki/"+entry)
    return HttpResponseRedirect(reverse("encyclopedia:error"))

def editPage(request, name):
    form = editPageForm(initial={'body': util.get_entry(name)})
    if request.method == "POST":
        form = editPageForm(request.POST)
        if form.is_valid():
            body = form.cleaned_data["body"]
            
            if name in util.list_entries():
                util.save_entry(name, body)
                return HttpResponseRedirect("/wiki/"+name)
    return render(request, "encyclopedia/editPage.html", {
        "form": form,
    })

wiki/encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Error Alert</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:page' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:searchPage' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" >
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}"> New Page </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    {% if Error %}
        Erro: This page already exists
    {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ content|safe }}
    <a href="{% url 'encyclopedia:editPage' title%}">Edit Page</a>
{% endblock %}